In [63]:
import numpy as np
import random 

In [64]:
#s box 
sbox = [
        0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76,
        0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0,
        0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15,
        0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07, 0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75,
        0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3, 0x29, 0xe3, 0x2f, 0x84,
        0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58, 0xcf,
        0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8,
        0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2,
        0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73,
        0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88, 0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb,
        0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac, 0x62, 0x91, 0x95, 0xe4, 0x79,
        0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a, 0xae, 0x08,
        0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a,
        0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e,
        0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf,
        0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68, 0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16
]
sboxInv = [
        0x52, 0x09, 0x6a, 0xd5, 0x30, 0x36, 0xa5, 0x38, 0xbf, 0x40, 0xa3, 0x9e, 0x81, 0xf3, 0xd7, 0xfb,
        0x7c, 0xe3, 0x39, 0x82, 0x9b, 0x2f, 0xff, 0x87, 0x34, 0x8e, 0x43, 0x44, 0xc4, 0xde, 0xe9, 0xcb,
        0x54, 0x7b, 0x94, 0x32, 0xa6, 0xc2, 0x23, 0x3d, 0xee, 0x4c, 0x95, 0x0b, 0x42, 0xfa, 0xc3, 0x4e,
        0x08, 0x2e, 0xa1, 0x66, 0x28, 0xd9, 0x24, 0xb2, 0x76, 0x5b, 0xa2, 0x49, 0x6d, 0x8b, 0xd1, 0x25,
        0x72, 0xf8, 0xf6, 0x64, 0x86, 0x68, 0x98, 0x16, 0xd4, 0xa4, 0x5c, 0xcc, 0x5d, 0x65, 0xb6, 0x92,
        0x6c, 0x70, 0x48, 0x50, 0xfd, 0xed, 0xb9, 0xda, 0x5e, 0x15, 0x46, 0x57, 0xa7, 0x8d, 0x9d, 0x84,
        0x90, 0xd8, 0xab, 0x00, 0x8c, 0xbc, 0xd3, 0x0a, 0xf7, 0xe4, 0x58, 0x05, 0xb8, 0xb3, 0x45, 0x06,
        0xd0, 0x2c, 0x1e, 0x8f, 0xca, 0x3f, 0x0f, 0x02, 0xc1, 0xaf, 0xbd, 0x03, 0x01, 0x13, 0x8a, 0x6b,
        0x3a, 0x91, 0x11, 0x41, 0x4f, 0x67, 0xdc, 0xea, 0x97, 0xf2, 0xcf, 0xce, 0xf0, 0xb4, 0xe6, 0x73,
        0x96, 0xac, 0x74, 0x22, 0xe7, 0xad, 0x35, 0x85, 0xe2, 0xf9, 0x37, 0xe8, 0x1c, 0x75, 0xdf, 0x6e,
        0x47, 0xf1, 0x1a, 0x71, 0x1d, 0x29, 0xc5, 0x89, 0x6f, 0xb7, 0x62, 0x0e, 0xaa, 0x18, 0xbe, 0x1b,
        0xfc, 0x56, 0x3e, 0x4b, 0xc6, 0xd2, 0x79, 0x20, 0x9a, 0xdb, 0xc0, 0xfe, 0x78, 0xcd, 0x5a, 0xf4,
        0x1f, 0xdd, 0xa8, 0x33, 0x88, 0x07, 0xc7, 0x31, 0xb1, 0x12, 0x10, 0x59, 0x27, 0x80, 0xec, 0x5f,
        0x60, 0x51, 0x7f, 0xa9, 0x19, 0xb5, 0x4a, 0x0d, 0x2d, 0xe5, 0x7a, 0x9f, 0x93, 0xc9, 0x9c, 0xef,
        0xa0, 0xe0, 0x3b, 0x4d, 0xae, 0x2a, 0xf5, 0xb0, 0xc8, 0xeb, 0xbb, 0x3c, 0x83, 0x53, 0x99, 0x61,
        0x17, 0x2b, 0x04, 0x7e, 0xba, 0x77, 0xd6, 0x26, 0xe1, 0x69, 0x14, 0x63, 0x55, 0x21, 0x0c, 0x7d
]

def subBytes(state):
    for i in range(len(state)):
        state[i] = sbox[state[i]]
    return state


def subBytesInv(state):
    for i in range(len(state)):
        state[i] = sboxInv[state[i]]



In [65]:
#shift row transformation
def Left_row_shift(state):
    state = list(state)
    offset = [ i for i in range(4)]
    for x in offset:
        for j in range(x):
            state.insert(x*4+3, state.pop(0 + x*4))

    return state

def Right_row_shift(state):
    offset = [ i for i in range(4)]
    for x in offset:
        for j in range(x):
            state.insert(x*4+0, state.pop(3 + x*4))

    return state


state = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# inv_state = Left_row_shift(state)
state2 = [1,2,3,4,6,7,8,5,11,12,9,10,16,13,14,15]
state = Right_row_shift(state2)
# print(state)


        

In [66]:
#galois multiplication
from copy import copy
import numpy as np
def g_mtp(a,b):
    if b == 1:
        return a
    elif b == 2:
        if a & 0x80 == 0x80:
            return ((a<<1)^(0x1b))& 255
        else:
            return (a<<1)& 255
    else:
        if a & 0x80 == 0x80:
            return ((a<<1)^(0x1b)^a)&255
        else:
            return ((a<<1)^a)&255 

    
def col_trans(state):
    new_state = np.zeros([4,4],dtype=int)
    
    A = np.array([
            [2,3,1,1],
            [1,2,3,1],
            [1,1,2,3],
            [3,1,1,2]])
        
    for j in range(len(state)):
        
        col = copy(state[:,j])
        x0,x1,x2,x3 = 0,0,0,0
        
        for i in range(4):

            x0 ^= g_mtp(col[i],A[0][i]) 
            x1 ^= g_mtp(col[i],A[1][i]) 
            x2 ^= g_mtp(col[i],A[2][i]) 
            x3 ^= g_mtp(col[i],A[3][i])
            x = [x0,x1,x2,x3]
        new_state[:,j] = [int(y) for y in x]
#         print(hex(x0),hex(x1),hex(x2),hex(x3))  
    return new_state


    


In [67]:
key = np.array([ord(i) for i in 'Thats my Kung Fu' ])

#key expansion
w0 = key[0:4]
w1 = key[4:8]
w2 = key[8:12]
w3 = key[12:16]

exp_key = np.array([w0,w1,w2,w3])
# print(exp_key)
def round_constant(i):
    rc = [0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80,0x1B,0x36]
    
    return rc[i]
    
    

def g(w3,i):
    w3 = list([int(x) for x in w3])
    w3 = w3[1:] + w3[:1]
    w3 = subBytes(w3)
    rc = round_constant(i)
    w3 = np.array(w3)^np.array([rc,0x00,0x00,0x00])

    return np.array([x for x in w3])


g_w3 = g(w3,0)
w4 = g_w3^w0

# print(w4)
exp_key = np.append(exp_key,[np.array(w4)],axis=0)

print(exp_key)
for i in range(5,44):
    if i%4 == 0:
        w = g(exp_key[i-1],int(i/4)-1)^exp_key[i-4]
    else:    
        w = exp_key[i-1]^exp_key[i-4]
    exp_key = np.append(exp_key,[w],axis=0)

    
for i in range(11):
    print(f"round key for round {i} : ")
    round_key = exp_key[4*i:4*(i+1)]
    round_key = [ [ hex(x) for x in y] for y in round_key]
    print(np.reshape(round_key,16))

[[ 84 104  97 116]
 [115  32 109 121]
 [ 32  75 117 110]
 [103  32  70 117]
 [226  50 252 241]]
round key for round 0 : 
['0x54' '0x68' '0x61' '0x74' '0x73' '0x20' '0x6d' '0x79' '0x20' '0x4b'
 '0x75' '0x6e' '0x67' '0x20' '0x46' '0x75']
round key for round 1 : 
['0xe2' '0x32' '0xfc' '0xf1' '0x91' '0x12' '0x91' '0x88' '0xb1' '0x59'
 '0xe4' '0xe6' '0xd6' '0x79' '0xa2' '0x93']
round key for round 2 : 
['0x56' '0x8' '0x20' '0x7' '0xc7' '0x1a' '0xb1' '0x8f' '0x76' '0x43'
 '0x55' '0x69' '0xa0' '0x3a' '0xf7' '0xfa']
round key for round 3 : 
['0xd2' '0x60' '0xd' '0xe7' '0x15' '0x7a' '0xbc' '0x68' '0x63' '0x39'
 '0xe9' '0x1' '0xc3' '0x3' '0x1e' '0xfb']
round key for round 4 : 
['0xa1' '0x12' '0x2' '0xc9' '0xb4' '0x68' '0xbe' '0xa1' '0xd7' '0x51'
 '0x57' '0xa0' '0x14' '0x52' '0x49' '0x5b']
round key for round 5 : 
['0xb1' '0x29' '0x3b' '0x33' '0x5' '0x41' '0x85' '0x92' '0xd2' '0x10'
 '0xd2' '0x32' '0xc6' '0x42' '0x9b' '0x69']
round key for round 6 : 
['0xbd' '0x3d' '0xc2' '0x87' '0xb8' '0x7c' '0x

In [68]:
msg = '1st16bytesoftext'
msg = np.array([ord(msg[j]) for j in range(len(msg))])
msg = np.reshape(msg,[4,4])
msg = np.transpose(msg)


In [69]:
#round 0
key = np.transpose(exp_key[0:4])
state = key^msg
print(np.array( [[hex(int(x)) for x in y] for y in state]))
print(np.reshape(state,16))

[['0x65' '0x45' '0x45' '0x13']
 ['0x1b' '0x42' '0x38' '0x45']
 ['0x15' '0x14' '0x1a' '0x3e']
 ['0x45' '0xd' '0x8' '0x1']]
[101  69  69  19  27  66  56  69  21  20  26  62  69  13   8   1]


In [70]:
def print_state(state):
    for x in state:
        for y in x:
            print(hex(y),end= " ")
        print()

#rounds 1-9
for i in range(1,10):
    key = np.transpose(exp_key[4*i:4*(i+1)])
    state = subBytes(np.reshape(state,16))
    state = Left_row_shift(np.reshape(state,16))
    state = col_trans(np.reshape(state,[4,4]))
#     print(state)
#     print( [[hex(x) for x in y] for y in state])
    state =  state^key
    print_state(state)
    print()

0xd2 0x98 0x51 0xc 
0xa6 0xd1 0xd7 0x64 
0x46 0x35 0x34 0xcf 
0x50 0x53 0xd6 0x21 

0x80 0x80 0xbd 0x4b 
0x14 0x96 0x17 0xdb 
0x87 0x3 0x5f 0x1b 
0x4 0x67 0xd9 0xa6 

0x13 0xc2 0xd5 0xe5 
0xf8 0x54 0x96 0xe7 
0xb9 0xc9 0x90 0xfe 
0xbc 0x84 0x30 0xde 

0x46 0x8b 0x7f 0xa7 
0x92 0xc5 0xc4 0x71 
0xb8 0xc9 0x8d 0x7c 
0x34 0x2f 0xd9 0xbf 

0xa1 0x53 0xea 0x47 
0xcb 0x6c 0x3e 0xc9 
0x65 0xac 0x44 0x76 
0x36 0xe9 0xba 0x75 

0xaf 0x89 0x50 0xb3 
0x1f 0xa3 0x83 0xec 
0x2a 0x67 0x77 0x8f 
0xbb 0xb9 0x19 0xc8 

0x3d 0x97 0x42 0x62 
0x17 0xf1 0x30 0x1e 
0x4c 0x22 0x89 0xea 
0xa9 0xa1 0x56 0x2b 

0x6e 0xa9 0x31 0x30 
0x2c 0x7a 0xbc 0xdb 
0x34 0xb2 0x20 0xe4 
0xb7 0x9f 0x4d 0x93 

0x84 0x97 0x27 0xb8 
0xcc 0x52 0x39 0xad 
0xf0 0x7e 0xb8 0xee 
0xe4 0x99 0xea 0x4f 



In [71]:
#round 10
key = np.transpose(exp_key[40:44])
state = subBytes(np.reshape(state,16))
state = Left_row_shift(np.reshape(state,16))
state = np.reshape(state,[4,4])
state =  state^key
print_state(state)


0x77 0xe5 0x0 0x57 
0xfd 0xb6 0x55 0x7a 
0xb2 0xc 0x28 0x9c 
0x7c 0x23 0x10 0xa1 


In [72]:
def print_chr(state):
    for x in state:
        for y in x:
            print(y,end= " ")
print_chr(state)

119 229 0 87 253 182 85 122 178 12 40 156 124 35 16 161 

In [73]:
print(len('DE561ED13F40DAB4CA2F4B0662FCD016B3E46F11BA8D2B97C18769449A89E868'))
print([hex(ord(i)) for i in 'hellohowareyou22'])

64
['0x68', '0x65', '0x6c', '0x6c', '0x6f', '0x68', '0x6f', '0x77', '0x61', '0x72', '0x65', '0x79', '0x6f', '0x75', '0x32', '0x32']


In [ ]:
# DECRYPTION STARTS NOW

